package com.wqd.pojo;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.username
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.depid
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    private Integer depid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.username
     *
     * @return the value of emp.username
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.username
     *
     * @param username the value for emp.username
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.depid
     *
     * @return the value of emp.depid
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    public Integer getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.depid
     *
     * @param depid the value for emp.depid
     *
     * @mbg.generated Sun Dec 11 17:00:34 CST 2022
     */
    public void setDepid(Integer depid) {
        this.depid = depid;
    }
}